---
title: "p8106_final"
author: "Zekai Jin, Zizhao Lin, Jiawen Zhao"
date: "2023-4-30"
output: html_document
---


```{r, echo=FALSE}
knitr::opts_chunk$set(
  message  = FALSE,
  warning = FALSE
)
```


```{r}
# Load the packages
library(tidyverse)
library(forcats)
library(ggridges)
library(corrplot)
library(patchwork)
library(caret)

# prepare the dataset
load("data/recovery.RData")

# sample from data
set.seed(2357) 
sample_1=sample(1:10000, 2000)
set.seed(3263) 
sample_2=sample(1:10000, 2000)

sample = c(sample_1,sample_2) %>% unique()

set.seed(1)

# preprocessing
dat = 
  dat[sample,] %>%
  janitor::clean_names() %>%
  mutate(
    gender=fct_recode(factor(gender),male='1',female='0'),
    race=fct_recode(factor(race),white='1',asian='2',black='3',hispanic='4'),
    smoking=fct_recode(factor(smoking),never='0',former='1',current='2'),
    hypertension=factor(hypertension),
    diabetes=factor(diabetes),
    vaccine=factor(vaccine),
    severity=factor(severity),
    study=factor(study),
  ) %>%
  select(-id)


# train-test splitting
sample = sample(c(TRUE, FALSE), nrow(dat), replace=TRUE, prob=c(0.8,0.2))
data_train = dat[sample,]
data_test = dat[!sample,]

# for parameter tuning
ctrl <- trainControl(method = "cv", number = 10)

```


# exploratory analysis

```{r}
# for continuous data
featurePlot(
  x = data_train %>% select(age,height,weight,bmi,sbp,ldl),
  y = data_train$recovery_time,
  plot = "scatter",
  span = .5,
  labels = c("Predictors","recovery_time"),
  type = c("p", "smooth"),
  layout = c(3, 2)
)
```

```{r}
# for catagorical data
p1 =
  data_train %>%
    ggplot() +
    geom_density_ridges(aes(x=recovery_time,y=gender,color=gender,fill=gender),alpha=0.5) +
    xlim(0,100)
p2 =
  data_train %>%
    ggplot() +
    geom_density_ridges(aes(x=recovery_time,y=race,color=race,fill=race),alpha=0.5)+
    xlim(0,100)
p3 =
  data_train %>%
    ggplot() +
    geom_density_ridges(aes(x=recovery_time,y=smoking,color=smoking,fill=smoking),alpha=0.5)+
    xlim(0,100)
p4 =
  data_train %>%
    ggplot() +
    geom_density_ridges(aes(x=recovery_time,y=hypertension,color=hypertension,fill=hypertension),alpha=0.5)+
    xlim(0,100)
p5 =
  data_train %>%
    ggplot() +
    geom_density_ridges(aes(x=recovery_time,y=diabetes,color=diabetes,fill=diabetes),alpha=0.5)+
    xlim(0,100)
p6 =
  data_train %>%
    ggplot() +
    geom_density_ridges(aes(x=recovery_time,y=vaccine,color=vaccine,fill=vaccine),alpha=0.5)+
    xlim(0,100)
p7 =
  data_train %>%
    ggplot() +
    geom_density_ridges(aes(x=recovery_time,y=severity,color=severity,fill=severity),alpha=0.5)+
    xlim(0,100)
p8=
  data_train %>%
    ggplot() +
    geom_density_ridges(aes(x=recovery_time,y=study,color=study,fill=study),alpha=0.5)+
    xlim(0,100)
(p1+p2+p3+p4)/(p5+p6+p7+p8)
```

```{r}
# correlation of continuous predictors
data_train %>%
  select(recovery_time,height,weight,bmi,sbp,ldl) %>%
  #model.matrix(recovery_time~.,.) %>%
  cor() %>%
  corrplot(.,type = "lower")
```


# building models
```{r,cache=TRUE}
# linear model
set.seed(1)
m_lm = 
  train(
    recovery_time~.,
    data = data_train,
    method = "lm",
    trControl = ctrl
  )
par(mfrow = c(2,2))
plot(m_lm$finalModel)

# elastic net for predictor selection
tune_grid = 
  expand.grid(
    alpha = 0:5/5,
    lambda = exp(-100:0/20)
  )

set.seed(1)
m_enet = 
  train(
    recovery_time~.,
    data = data_train,
    method = "glmnet",
    tuneGrid = tune_grid,
    trControl = ctrl
  )
plot(m_enet)
```
